### PR TITLE
Use versioneer for version numbering

### PR DESCRIPTION
**Pull request by mwcraig**
This PR adds versioneer to handle the version numbering. If the CI builds on travis and appveyor pass then this is ready to be merged.

### CODE REVIEW

**Comment by BruceSherwood** [comment]
I don't see the required change to vpython.py, to change line 51, version = ['0.3.11', 'jupyter'], to something that uses the versioneer value.

**Comment by mwcraig** [comment]
Oops, just fixed that, thanks for catching it. I also added a bit of regular expression stuff to extract the glowscript version from the glowscript javascript source.

**Comment by mwcraig** [comment]
This is ready to merge, I think, @BruceSherwood

**Comment by BruceSherwood** [comment]
Merged.

**Pull request merged**
