### PR TITLE
Simplify notebook logic

### LINKED ISSUE #73: Notebook demo does not run with combination IPython 7, ipykernel 4
With the latest master, the notebook demos do not run with the combination of IPython 7 and ipykernel 4. I *think* the fix is to remove the check for `IPython.__version__ >= '7.0.0'` that is now at https://github.com/BruceSherwood/vpython-jupyter/pull/59/files#diff-0999d0903bd243aeab01d37a27725cc4R250

Someone else should check this too...

### LINKED ISSUE #74: Check that latest version works with IPython 7/ipykernel 5
I think this already the case, but it never hurts to check...

### LINKED ISSUE #75: Check that latest works with IPython 6/ ipykernel 5
This combination of versions may be unlikely, but we may as well check it.

### LINKED ISSUE #76: Check that latest notebook demos run with IPython 6/ipykernel 4
This will be a common case

### LINKED ISSUE #77: Update installer to relax constraint on ipykernel version
Right now it is restricted to 4.x. Gogin forward a restriction to 5.x or lower makes sense. An upper bound is important to avoid problems when ipykernel 6 is eventually released.

### PR DESCRIPTION
**Pull request by mwcraig**
This removes version checks for ipython and ipykernel. I will set a minimum version for IPython in the setup.py to 4 (ipykernel started at version 4 so no need for a minimum version for that).

Fixes #73 (was bug)

Issues below were compatibility checks:

Fixes #74 
Fixes #75 
Fixes #76 
Fixes #77

### CODE REVIEW

**Comment by mwcraig** [comment]
@jcoady — do these changes look ok? I’ve tested with ipykernel 4 and 5, on lab and notebook...

**Comment by jcoady** [comment]
Matt if you use the websocket in ipykernel 4.x to receive messages from the front end over the websocket instead of the comm channel then you should also make the change in rate_control.py to check ipykernel 4.x instead of ipykernel 5.0.0 .  If messages are received over the comm channel then we call kernel.do_one_iteration() method but if they are received over the websocket then we don't need to call kernel.do_one_iteration(). You should test your changes again with the change in rate_control.py to check that everything works properly.

**Comment by mwcraig** [comment]
Looks like this works with Ipython 6/7 and ipykernel 4/5 (all four combinations of those possibilities) in both jupyter notebook and lab.

**Comment by mwcraig** [comment]
I'm going to go ahead and merge this....

**Pull request merged**
